import cors from "cors";
import dotenv from "dotenv";
import express from "express";
import { executeComponent } from "@zhanla/sdk-ts";
import { newsImpactPipeline } from "./agent.js";

dotenv.config();

const app = express();
const port = process.env.PORT || 3000;

// Enable CORS so the Chrome Extension can make requests from its chrome-extension:// origin
app.use(cors());

// Parse JSON payloads
app.use(express.json());

// Log incoming requests
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);
  next();
});

// Health check endpoint
app.get("/health", (req, res) => {
  res.json({ status: "ok", time: new Date() });
});

// Primary endpoint for the Chrome Extension to trigger news stock analysis
app.post("/api/analyze", async (req, res) => {
  try {
    const { newsText, watchlist } = req.body;

    if (!newsText || typeof newsText !== "string") {
      return res.status(400).json({ error: "Missing or invalid parameter: newsText" });
    }

    if (!watchlist || !Array.isArray(watchlist)) {
      return res.status(400).json({ error: "Missing or invalid parameter: watchlist (must be an array of stock symbols)" });
    }

    console.log(`Starting stock impact analysis for watchlist: [${watchlist.join(", ")}]`);
    console.log(`News content snippet: "${newsText.substring(0, 100)}..."`);

    // Run the Zhanla newsImpactPipeline using the local executor
    const start = Date.now();
    const result = await executeComponent(newsImpactPipeline, {
      newsText,
      watchlist
    });
    const duration = Date.now() - start;

    console.log(`Analysis completed successfully in ${duration}ms. Output:`, JSON.stringify(result, null, 2));

    // Return the structured impact output generated by our LLM agent pipeline
    res.json({
      success: true,
      data: result,
      durationMs: duration
    });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    console.error("Error executing news impact pipeline:", error);
    res.status(500).json({
      success: false,
      error: "An error occurred during stock news analysis",
      details: errorMessage
    });
  }
});

// Start the Express server
app.listen(port, () => {
  console.log(`==================================================`);
  console.log(` Zhanla Stock Analysis Server is running!`);
  console.log(` Port: ${port}`);
  console.log(` Endpoint: http://localhost:${port}/api/analyze`);
  console.log(`==================================================`);
});
